config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [ :index, :show ] do
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
  validates :content, length: {minimum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new  # Add this line
  end
end

app/controllers/reviews_controller.rb
# app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render "restaurants/show", status: :unprocessable_entity }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end

  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxInRails1041</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_review.html.erb
<p><%= review.content %></p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<!-- app/views/restaurants/show.html.erb -->
<h1><%= @restaurant.name %> <small><%= @restaurant.address %></small></h1>

<h2><%= pluralize @restaurant.reviews.size, "review" %></h2>

<div data-controller="insert-in-list">
  <div data-insert-in-list-target="items">
    <% if @restaurant.reviews.blank? %>
      Be the first to leave a review for <%= @restaurant.name %>
    <% else %>
      <% @restaurant.reviews.each do |review| %>
        <%= render "review", review: review %>
      <% end %>
    <% end %>
  </div>
  <%= render "reviews/form", restaurant: @restaurant, review: @review %>
</div>

<%= link_to "Back to all restaurants", restaurants_path %>

<%= link_to "Back to all restaurants", restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for([restaurant, review], data: {insert_in_list_target: "form",
action: "submit->insert-in-list#send" }) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>